deny = [
  # Forbid
  "clippy::empty_drop",
  "clippy::exit",
  "clippy::large_futures",
  "clippy::mem_forget",
  "clippy::mod_module_files",
  "clippy::rc_mutex",
  "clippy::wildcard_dependencies",
  "non_ascii_idents",
  # Deny
  "clippy::cast_possible_truncation",
  "clippy::cast_possible_wrap",
  "clippy::cast_precision_loss",
  "clippy::cast_ptr_alignment",
  "clippy::cast_sign_loss",
  "clippy::checked_conversions",
  "clippy::clone_on_ref_ptr",
  "clippy::cloned_instead_of_copied",
  "clippy::empty_drop",
  "clippy::expl_impl_clone_on_copy",
  "clippy::explicit_deref_methods",
  "clippy::fn_to_numeric_cast_any",
  "clippy::get_unwrap",
  "clippy::iter_not_returning_iterator",
  "clippy::macro_use_imports",
  "clippy::mut_mut",
  "clippy::negative_feature_names",
  "clippy::ref_option_ref",
  "clippy::same_functions_in_if_condition",
  "clippy::string_add",
  "clippy::string_add_assign",
  "clippy::string_to_string",
  "clippy::unnecessary_self_imports",
  "clippy::unsafe_derive_deserialize",
  "let_underscore_drop",
  "noop_method_call",
  "unsafe_code",
  "unused_results"
]

warn = [
  "clippy::arithmetic_side_effects",
  "clippy::empty_structs_with_brackets",
  "clippy::cast_possible_truncation",
  "clippy::bool_to_int_with_if",
  "clippy::cargo-common-metadata",
  "clippy::cast_lossless",
  "clippy::dbg_macro",
  "clippy::default_trait_access",
  "clippy::doc_link_with_quotes",
  "clippy::doc_markdown",
  "clippy::empty_structs_with_brackets",
  "clippy::explicit_into_iter_loop",
  "clippy::explicit_iter_loop",
  "clippy::fn_params_excessive_bools",
  "clippy::from_iter_instead_of_collect",
  "clippy::if_not_else",
  "clippy::if_then_some_else_none",
  "clippy::implicit_clone",
  "clippy::indexing_slicing",
  "clippy::inefficient_to_string",
  "clippy::integer_division",
  "clippy::large_digit_groups",
  "clippy::large_include_file",
  "clippy::large_stack_arrays",
  "clippy::large_types_passed_by_value",
  "clippy::let_underscore_must_use",
  "clippy::linkedlist",
  "clippy::lossy_float_literal",
  "clippy::manual_assert",
  "clippy::manual_instant_elapsed",
  "clippy::manual_let_else",
  "clippy::manual_ok_or",
  "clippy::manual_string_new",
  "clippy::many_single_char_names",
  "clippy::map_err_ignore",
  "clippy::map_unwrap_or",
  "clippy::match_bool",
  "clippy::match_on_vec_items",
  "clippy::match_same_arms",
  "clippy::match_wild_err_arm",
  "clippy::match_wildcard_for_single_variants",
  "clippy::maybe_infinite_iter",
  "clippy::missing_assert_message",
  "clippy::missing_enforced_import_renames",
  "clippy::missing_errors_doc",
  "clippy::missing_panics_doc",
  "clippy::multiple_unsafe_ops_per_block",
  "clippy::needless_continue",
  "clippy::needless_for_each",
  "clippy::option_option",
  "clippy::panic_in_result_fn",
  "clippy::partial_pub_fields",
  "clippy::ptr_as_ptr",
  "clippy::range_minus_one",
  "clippy::range_plus_one",
  "clippy::rc_buffer",
  "clippy::redundant_closure_for_method_calls",
  "clippy::redundant_else",
  "clippy::redundant_feature_names",
  "clippy::rest_pat_in_fully_bound_structs",
  "clippy::same_name_method",
  "clippy::semicolon_if_nothing_returned",
  "clippy::semicolon_inside_block",
  "clippy::single_match_else",
  "clippy::str_to_string",
  "clippy::string_slice",
  "clippy::struct_excessive_bools",
  "clippy::tests_outside_test_module",
  "clippy::todo",
  "clippy::too_many_lines",
  "clippy::try_err",
  "clippy::unchecked_duration_subtraction",
  "clippy::undocumented_unsafe_blocks",
  "clippy::unimplemented",
  "clippy::uninlined_format_args",
  "clippy::unnecessary_box_returns",
  "clippy::unnecessary_join",
  "clippy::unnecessary_safety_comment",
  "clippy::unnecessary_safety_doc",
  "clippy::unnecessary_wraps",
  "clippy::unneeded_field_pattern",
  "clippy::unreadable_literal",
  "clippy::unseparated_literal_suffix",
  "clippy::unused_async",
  "clippy::unwrap_in_result",
  "clippy::unwrap_used",
  "clippy::use_debug",
  "clippy::used_underscore_binding",
  "clippy::verbose_file_reads",
  "explicit_outlives_requirements",
  "missing_docs",
  "missing_copy_implementations",
  "missing_debug_implementations",
  "single_use_lifetimes",
  "trivial_casts",
  "trivial_numeric_casts",
  "unreachable_pub",
  "unused_crate_dependencies",
  "unused_import_braces",
  "unused_lifetimes",
  "unused_macro_rules",
  "unused_qualifications",
  "unused_tuple_struct_fields"
]
